version: '2.4'

services:  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1-1-ubi8
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SASL_ENABLED: "false"
    mem_limit: 128m
    healthcheck:
      test: "nc -z 127.0.0.1 2181"
      interval: 10s
      timeout: 10s
      retries: 10

  kafka:
    image: confluentinc/cp-kafka:7.2.1-1-ubi8
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "false"
      KAFKA_LISTENERS: LISTENER_PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29091
      KAFKA_ADVERTISED_LISTENERS: LISTENER_PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SCHEMA_REGISTRY_URL: http://schema_registry:8085
      CONFLUENT_SUPPORT_METRICS_ENABLE: 1
      # KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      # CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:9092
      # CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: false
      # CONFLUENT_METRICS_REPORTER_MAX_REQUEST_SIZE: 10485760
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_JMX_PORT: 9991
    mem_limit: 768m
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    healthcheck:
      test: "bash -c 'echo Waiting for Kafka to be ready... && cub kafka-ready -b kafka:9092 1 20'"
      interval: 10s
      timeout: 10s
      retries: 10

  schema_registry:
    image: confluentinc/cp-schema-registry:7.2.1-1-ubi8
    hostname: schema_registry
    container_name: schema_registry
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085
    ports:
      - 8085:8085

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.2.1-1-ubi8
    hostname: control-center
    container_name: control-center
    depends_on:
      - zookeeper
      - kafka
      # - schema_registry
    ports:
      - 9021:9021
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://0.0.0.0:8085
      CONFLUENT_CONTROL_CENTRE_CONNECT_HEALTHCHECK_ENDPOINT: /connectors
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      # CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      # CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      # CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021